name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.3.4

homepage: https://masterme.ru

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  xml: ^4.5.1
  cryptoutils: ^0.4.0
  crypto: ^2.1.5
  synchronized: ^2.2.0+2
  tuple: ^1.0.3
  unorm_dart: ^0.1.2
  image: ^2.1.19
  quiver: ^2.1.5 # hash code generator
  console: ^3.1.0 # for example
  intl: ^0.16.1

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
